### ISSUE TITLE
improve keyboard only usage

### ISSUE THREAD

**Issue by Buster-de** [linuxmuster/linuxmuster-linbo-gui#59]
from [this thread](https://ask.linuxmuster.net/t/meine-ersten-erfahrungen-mit-lmn-v7/7395):

- highlighting of focused element is barely visible on some buttons
  - maybe increase width or add some drop shadow to the whole button
- buttons have no visible border - clickable area should be distinct from non-clickable areas
  -  maybe add some shadow or border line
- pressing tab once does not always focus first visible element, sometimes you need to press tab a 2nd or 3rd time to have the 1st element highlighted
- pressing `space` or `enter` on numeric keypad should trigger action of selected element (as normal `enter` does)

**Comment by dorianim** [comment]
Regarding your first and second proposal:
I have spent a lot of time trying different styles. especially for the tab focus. I ended up choosing this one, because it is simple. Having a border around buttons just does not look good in many cases. Thats why I designed it as it is right now.
There are several problems with changing the button size on demand and I don't think it would look good either. 
I will see if I can improove visibility of the highlighting on the OS buttons though, you go a point there.

Regarding your third proposal:
Qt's api has lots of limitaions regarding the tab order. I have already spent lots of efforts trying to make the tab order as good as possible. Usually, pressing tab once will always focus the firs OS buttton, where did that not work for you?

Regarding your thrid proposal:
I am not sure why this is a problem. It may be caused by the keyboard driver. I will look into this but I am not sure if I can fix it.

**Comment by dorianim** [comment]
> pressing space or enter on numeric keypad should trigger action of selected element (as normal enter does)

Unfortunately, Qt recognizes these keys as a different key internally (`Qt::Key_Return` and `Qt::Key_Enter`) and does not allow changing which keys execute a focused button.

I changed the look of the focus bar a bit to make it better visible.

**Comment by Buster-de** [comment]
It should be possible to catch any key press event

https://wiki.qt.io/How_to_catch_enter_key

**Comment by dorianim** [comment]
Yes, but that does not really help.
It is possible to catch the key event (I am already doing that for several other keys) but when I catch that event, what do I do next? How do I know which action should be executed? It would be possible to hack that together with some effort, but that would not be clean and in my opiniom it's not woth it...
Is it really that important?
